"""
Week 04 EXERCISE STARTER -- Intro to Unit Testing in Python
ITIA 1510 Cybersecurity Automation

Three small functions that a login service could use to decide how to treat a
user after failed sign-in attempts. Each docstring states exactly what the
function is supposed to return. One of the three does not do what its
docstring says.

Do not edit this file yet. Write the tests first, in a separate file named
test_login_rules.py, and let the tests find the problem.
"""


def is_locked_out(failed_attempts, limit):
    """True when failed_attempts is limit or more."""
    return failed_attempts >= limit


def session_expired(minutes_idle, timeout):
    """True when minutes_idle is more than timeout."""
    return minutes_idle > timeout


def risk_level(failed_attempts):
    """'LOW' for 0 to 2 attempts, 'MEDIUM' for 3 to 5, 'HIGH' for 6 or more."""
    if failed_attempts >= 6:
        return "HIGH"
    elif failed_attempts >= 3:
        return "MEDIUM"
    else:
        return "LOW"


if __name__ == '__main__': 
    attempts = int(input("Failed attempts: "))
    print("Locked out (limit 5): " + str(is_locked_out(attempts, 5)))
    print("Risk level:           " + risk_level(attempts))
